"""Regenerates src/mdi-subset.css: the Material Design Icons the web app uses, as CSS masks
(no icon font to download). Run it after using a new `mdi mdi-<name>` class:

    python scripts/gen-mdi-subset.py

Finds every literal icon name in src/ and App.jsx (mdi-<name>, icon="<name>", icon: '<name>' and the
Sidebar ICONS map) and downloads each SVG path from @mdi/svg (Apache-2.0).
"""
import base64
import glob
import re
import urllib.request

VERSION = "7.4.47"
names = set()
for path in glob.glob("src/**/*.jsx", recursive=True) + ["App.jsx"]:
    text = open(path, encoding="utf-8-sig").read()
    names |= set(re.findall(r"mdi-([a-z][a-z0-9-]*[a-z0-9])", text))
    names |= set(re.findall(r"icon[=:] ?[\"']([a-z0-9-]+)[\"']", text))
sidebar = open("src/components/Sidebar.jsx", encoding="utf-8").read()
names |= set(re.findall(r": '([a-z0-9-]+)',", sidebar[: sidebar.index("const Sidebar")]))

rules = [
    f"/* Material Design Icons subset (Apache-2.0, @mdi/svg {VERSION}): only the icons the app uses, as CSS masks.",
    "   The icon inherits `color` and `font-size`, like the old icon font. Generated by scripts/gen-mdi-subset.py. */",
    ".mdi { display: inline-block; width: 1em; height: 1em; flex-shrink: 0; vertical-align: -0.125em; background-color: currentColor; -webkit-mask: var(--mdi) center / contain no-repeat; mask: var(--mdi) center / contain no-repeat; }",
]
missing = []
for name in sorted(names):
    try:
        svg = urllib.request.urlopen(f"https://cdn.jsdelivr.net/npm/@mdi/svg@{VERSION}/svg/{name}.svg", timeout=20).read().decode()
    except Exception:
        missing.append(name)
        continue
    d = re.search(r'<path d="([^"]+)"', svg).group(1)
    icon = f'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="{d}"/></svg>'
    rules.append(f'.mdi-{name} {{ --mdi: url("data:image/svg+xml;base64,{base64.b64encode(icon.encode()).decode()}"); }}')
open("src/mdi-subset.css", "w", encoding="utf-8").write("\n".join(rules) + "\n")
print(len(rules) - 3, "icons;", "not in @mdi/svg (ignored):", missing)
