-- Perfume Inventory Management System - PostgreSQL schema (Supabase / hosted Postgres)
-- Generated by Hibernate 6 (ddl-auto=update) against an empty Postgres 17 and dumped with
-- pg_dump --schema-only --no-owner --no-privileges. Production runs with DDL_AUTO=validate, so the
-- app never alters this schema; change it here and re-apply deliberately.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    access_time timestamp(6) without time zone NOT NULL,
    endpoint character varying(500) NOT NULL,
    ip_address character varying(45),
    method character varying(10) NOT NULL,
    user_agent character varying(500),
    usuario_id bigint
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_logs_id_seq OWNED BY public.audit_logs.id;


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(100),
    endereco character varying(255),
    nome character varying(200) NOT NULL,
    telefone character varying(20),
    updated_at timestamp(6) without time zone
);


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clientes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clientes_id_seq OWNED BY public.clientes.id;


--
-- Name: fornecedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fornecedores (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    cep character varying(10),
    cidade character varying(100),
    cnpj character varying(18),
    contato_principal character varying(100),
    created_at timestamp(6) without time zone,
    email character varying(100),
    endereco character varying(255),
    estado character varying(2),
    nome_fantasia character varying(200),
    razao_social character varying(200) NOT NULL,
    telefone character varying(20),
    updated_at timestamp(6) without time zone
);


--
-- Name: fornecedores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.fornecedores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: fornecedores_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.fornecedores_id_seq OWNED BY public.fornecedores.id;


--
-- Name: linhas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.linhas (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    descricao character varying(500),
    nome character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    marca_id bigint NOT NULL
);


--
-- Name: linhas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.linhas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: linhas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.linhas_id_seq OWNED BY public.linhas.id;


--
-- Name: lotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lotes (
    id bigint NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    data_fabricacao date,
    data_validade date NOT NULL,
    localizacao_arquivo character varying(100),
    numero_lote character varying(50) NOT NULL,
    preco_custo_lote numeric(10,2),
    quantidade integer NOT NULL,
    status character varying(20),
    unidade_medida character varying(20),
    atualizado_por bigint,
    criado_por bigint NOT NULL,
    fornecedor_id bigint,
    produto_id bigint NOT NULL,
    CONSTRAINT lotes_status_check CHECK (((status)::text = ANY ((ARRAY['ATIVO'::character varying, 'VENCIDO'::character varying, 'RESERVADO'::character varying, 'BLOQUEADO'::character varying])::text[]))),
    CONSTRAINT lotes_unidade_medida_check CHECK (((unidade_medida)::text = ANY ((ARRAY['UNIDADE'::character varying, 'CAIXA'::character varying, 'FRASCO'::character varying, 'ML'::character varying, 'L'::character varying, 'G'::character varying, 'KG'::character varying])::text[])))
);


--
-- Name: lotes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.lotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: lotes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.lotes_id_seq OWNED BY public.lotes.id;


--
-- Name: marcas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marcas (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    descricao character varying(500),
    logo_url character varying(255),
    nome character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: marcas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.marcas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: marcas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.marcas_id_seq OWNED BY public.marcas.id;


--
-- Name: movimentacoes_estoque; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimentacoes_estoque (
    id bigint NOT NULL,
    data_movimentacao timestamp(6) without time zone NOT NULL,
    estrategia character varying(20),
    motivo character varying(20),
    quantidade integer NOT NULL,
    tipo character varying(10) NOT NULL,
    produto_id bigint NOT NULL,
    usuario_id bigint,
    CONSTRAINT movimentacoes_estoque_motivo_check CHECK (((motivo)::text = ANY ((ARRAY['COMPRA_RECEBIDA'::character varying, 'ESTOQUE_INICIAL'::character varying, 'VENDA'::character varying, 'DEVOLUCAO'::character varying, 'DANIFICADO'::character varying, 'VENCIDO'::character varying, 'PERDA'::character varying, 'CORRECAO_CONTAGEM'::character varying, 'OUTRO'::character varying])::text[]))),
    CONSTRAINT movimentacoes_estoque_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


--
-- Name: movimentacoes_estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.movimentacoes_estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: movimentacoes_estoque_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.movimentacoes_estoque_id_seq OWNED BY public.movimentacoes_estoque.id;


--
-- Name: notificacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificacoes (
    id bigint NOT NULL,
    dados_adicionais character varying(2000),
    data_criacao timestamp(6) without time zone,
    data_envio timestamp(6) without time zone,
    data_processamento timestamp(6) without time zone,
    lote_id bigint,
    mensagem character varying(1000),
    produto_id bigint,
    status character varying(20) NOT NULL,
    tipo character varying(30) NOT NULL,
    titulo character varying(200) NOT NULL,
    CONSTRAINT notificacoes_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PROCESSADO'::character varying, 'ENVIADO'::character varying, 'FALHOU'::character varying])::text[]))),
    CONSTRAINT notificacoes_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ESTOQUE_CRITICO'::character varying, 'VENCIMENTO_PROXIMO'::character varying, 'VENCIDO'::character varying])::text[])))
);


--
-- Name: notificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notificacoes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notificacoes_id_seq OWNED BY public.notificacoes.id;


--
-- Name: pedido_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedido_itens (
    id bigint NOT NULL,
    preco_unitario numeric(10,2) NOT NULL,
    quantidade integer NOT NULL,
    pedido_id bigint NOT NULL,
    produto_id bigint NOT NULL
);


--
-- Name: pedido_itens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pedido_itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pedido_itens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pedido_itens_id_seq OWNED BY public.pedido_itens.id;


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    data_atualizacao timestamp(6) without time zone,
    data_criacao timestamp(6) without time zone,
    observacoes character varying(500),
    status character varying(20) NOT NULL,
    valor_total numeric(12,2),
    cliente_id bigint NOT NULL,
    criado_por bigint,
    CONSTRAINT pedidos_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'CONFIRMADO'::character varying, 'ENVIADO'::character varying, 'ENTREGUE'::character varying, 'CANCELADO'::character varying])::text[])))
);


--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pedidos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pedidos_id_seq OWNED BY public.pedidos.id;


--
-- Name: produtos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produtos (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    altura_cm numeric(5,2),
    barcode_ean13 character varying(13),
    barcode_upc character varying(12),
    created_at timestamp(6) without time zone,
    descricao character varying(1000),
    estoque_maximo integer NOT NULL,
    estoque_minimo integer NOT NULL,
    fragrancia character varying(100),
    largura_cm numeric(5,2),
    margem_lucro_percentual numeric(5,2),
    nome character varying(200) NOT NULL,
    peso_gramas numeric(8,3),
    preco_custo numeric(10,2) NOT NULL,
    preco_venda numeric(10,2) NOT NULL,
    profundidade_cm numeric(5,2),
    sku character varying(50) NOT NULL,
    tipo_produto character varying(50),
    updated_at timestamp(6) without time zone,
    linha_id bigint NOT NULL
);


--
-- Name: produtos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: produtos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.produtos_id_seq OWNED BY public.produtos.id;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    failed_login_attempts integer NOT NULL,
    full_name character varying(100) NOT NULL,
    last_login timestamp(6) without time zone,
    locked_until timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'OPERATOR'::character varying, 'MANAGER'::character varying, 'AUDITOR'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: audit_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs ALTER COLUMN id SET DEFAULT nextval('public.audit_logs_id_seq'::regclass);


--
-- Name: clientes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes ALTER COLUMN id SET DEFAULT nextval('public.clientes_id_seq'::regclass);


--
-- Name: fornecedores id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores ALTER COLUMN id SET DEFAULT nextval('public.fornecedores_id_seq'::regclass);


--
-- Name: linhas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linhas ALTER COLUMN id SET DEFAULT nextval('public.linhas_id_seq'::regclass);


--
-- Name: lotes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes ALTER COLUMN id SET DEFAULT nextval('public.lotes_id_seq'::regclass);


--
-- Name: marcas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marcas ALTER COLUMN id SET DEFAULT nextval('public.marcas_id_seq'::regclass);


--
-- Name: movimentacoes_estoque id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque ALTER COLUMN id SET DEFAULT nextval('public.movimentacoes_estoque_id_seq'::regclass);


--
-- Name: notificacoes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes ALTER COLUMN id SET DEFAULT nextval('public.notificacoes_id_seq'::regclass);


--
-- Name: pedido_itens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens ALTER COLUMN id SET DEFAULT nextval('public.pedido_itens_id_seq'::regclass);


--
-- Name: pedidos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos ALTER COLUMN id SET DEFAULT nextval('public.pedidos_id_seq'::regclass);


--
-- Name: produtos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos ALTER COLUMN id SET DEFAULT nextval('public.produtos_id_seq'::regclass);


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: fornecedores fornecedores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores
    ADD CONSTRAINT fornecedores_pkey PRIMARY KEY (id);


--
-- Name: linhas linhas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linhas
    ADD CONSTRAINT linhas_pkey PRIMARY KEY (id);


--
-- Name: lotes lotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT lotes_pkey PRIMARY KEY (id);


--
-- Name: marcas marcas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes_estoque movimentacoes_estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT movimentacoes_estoque_pkey PRIMARY KEY (id);


--
-- Name: notificacoes notificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id);


--
-- Name: pedido_itens pedido_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens
    ADD CONSTRAINT pedido_itens_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);


--
-- Name: produtos uk_dkrdsbcps8g523s1tyb3vide5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT uk_dkrdsbcps8g523s1tyb3vide5 UNIQUE (barcode_ean13);


--
-- Name: produtos uk_fl77yts0xdndf3o87ag7kaug8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT uk_fl77yts0xdndf3o87ag7kaug8 UNIQUE (barcode_upc);


--
-- Name: usuarios uk_kfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk_kfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: usuarios uk_m2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk_m2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- Name: marcas uk_r2am2bysorcd90qxo9mscxahg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT uk_r2am2bysorcd90qxo9mscxahg UNIQUE (nome);


--
-- Name: produtos uk_t48jr33lgp3ogqymt7ixddi1n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT uk_t48jr33lgp3ogqymt7ixddi1n UNIQUE (sku);


--
-- Name: fornecedores uk_tflo0rfxyagqf5aq6rvjt5ofh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedores
    ADD CONSTRAINT uk_tflo0rfxyagqf5aq6rvjt5ofh UNIQUE (cnpj);


--
-- Name: linhas ukex1yj1bhs3kavkgnmqbb7kc5d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linhas
    ADD CONSTRAINT ukex1yj1bhs3kavkgnmqbb7kc5d UNIQUE (marca_id, nome);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: idx_access_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_access_time ON public.audit_logs USING btree (access_time);


--
-- Name: idx_data_criacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_criacao ON public.notificacoes USING btree (data_criacao);


--
-- Name: idx_data_validade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_validade ON public.lotes USING btree (data_validade);


--
-- Name: idx_endpoint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_endpoint ON public.audit_logs USING btree (endpoint);


--
-- Name: idx_ip_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ip_address ON public.audit_logs USING btree (ip_address);


--
-- Name: idx_mov_data; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mov_data ON public.movimentacoes_estoque USING btree (data_movimentacao);


--
-- Name: idx_mov_produto; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mov_produto ON public.movimentacoes_estoque USING btree (produto_id);


--
-- Name: idx_numero_lote; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_numero_lote ON public.lotes USING btree (numero_lote);


--
-- Name: idx_produto_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_produto_status ON public.lotes USING btree (produto_id, status);


--
-- Name: idx_tipo_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tipo_status ON public.notificacoes USING btree (tipo, status);


--
-- Name: produtos fk12sd74dd12gan1akt3v7md1b1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT fk12sd74dd12gan1akt3v7md1b1 FOREIGN KEY (linha_id) REFERENCES public.linhas(id);


--
-- Name: pedidos fk3hxga98bpk2fi048524899n77; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk3hxga98bpk2fi048524899n77 FOREIGN KEY (criado_por) REFERENCES public.usuarios(id);


--
-- Name: movimentacoes_estoque fk6pku6boilr8s834gvqtw0f0p5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fk6pku6boilr8s834gvqtw0f0p5 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: pedido_itens fka3dnlbbof21fsp6gnngyqix1e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens
    ADD CONSTRAINT fka3dnlbbof21fsp6gnngyqix1e FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id);


--
-- Name: pedidos fkg7202lk0hwxn04bmdl2thth5b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fkg7202lk0hwxn04bmdl2thth5b FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: pedido_itens fkh3vmat7mmgte1ibndam2o6lqx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedido_itens
    ADD CONSTRAINT fkh3vmat7mmgte1ibndam2o6lqx FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: lotes fkh9sk47tuay9lg65rv7bl7xd4p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT fkh9sk47tuay9lg65rv7bl7xd4p FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id);


--
-- Name: movimentacoes_estoque fkmdn52qx0fmc71ejys5cmetpjc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkmdn52qx0fmc71ejys5cmetpjc FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: audit_logs fkp9u15a4jtmfnav3105c5d7rhm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fkp9u15a4jtmfnav3105c5d7rhm FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: lotes fkqexy7wuxwrcg2dva37p4c1b7y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT fkqexy7wuxwrcg2dva37p4c1b7y FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- Name: lotes fkqkagx6clg5b0drbdamh20w6xr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT fkqkagx6clg5b0drbdamh20w6xr FOREIGN KEY (atualizado_por) REFERENCES public.usuarios(id);


--
-- Name: linhas fkrms7iu18e9vdp9pgripi618jx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.linhas
    ADD CONSTRAINT fkrms7iu18e9vdp9pgripi618jx FOREIGN KEY (marca_id) REFERENCES public.marcas(id);


--
-- Name: lotes fksf0jsd6i0lwrory4ytauo0u1e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT fksf0jsd6i0lwrory4ytauo0u1e FOREIGN KEY (criado_por) REFERENCES public.usuarios(id);


--
-- PostgreSQL database dump complete
--


