-- Revistas: a brand's magazine, stored as one JPEG per page (see RevistaService).
-- Self-contained: paste the whole file in the Supabase SQL editor (or run it with
-- `node --env-file=.env.supabase apply-schema.mjs 002_revistas.sql`). It creates the tables AND does
-- what harden.mjs does for them (row level security + DML-only grants for the backend role).

CREATE TABLE IF NOT EXISTS public.revistas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    titulo character varying(150) NOT NULL,
    total_paginas integer NOT NULL,
    marca_id bigint NOT NULL REFERENCES public.marcas(id)
);

CREATE INDEX IF NOT EXISTS revistas_marca_id_idx ON public.revistas (marca_id);

-- numero 0 is the cover thumbnail, 1..total_paginas are the pages.
CREATE TABLE IF NOT EXISTS public.revista_paginas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagem bytea NOT NULL,
    numero integer NOT NULL,
    revista_id bigint NOT NULL REFERENCES public.revistas(id),
    CONSTRAINT revista_paginas_revista_numero_key UNIQUE (revista_id, numero)
);

-- Lock the new tables down like every other one: nobody but the backend role (estoque_app) sees them,
-- not even through the Supabase Data API (anon / authenticated).
REVOKE ALL ON public.revistas, public.revista_paginas FROM PUBLIC, anon, authenticated;

ALTER TABLE public.revistas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revista_paginas ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'estoque_app') THEN
        DROP POLICY IF EXISTS app_access ON public.revistas;
        CREATE POLICY app_access ON public.revistas FOR ALL TO estoque_app USING (true) WITH CHECK (true);
        DROP POLICY IF EXISTS app_access ON public.revista_paginas;
        CREATE POLICY app_access ON public.revista_paginas FOR ALL TO estoque_app USING (true) WITH CHECK (true);
        GRANT SELECT, INSERT, UPDATE, DELETE ON public.revistas, public.revista_paginas TO estoque_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO estoque_app;
    ELSE
        RAISE NOTICE 'role estoque_app not found: tables created but not granted; run harden.mjs';
    END IF;
END
$$;
