-- Revistas: a brand's magazine, stored as one JPEG per page (see RevistaService).
-- Apply as the OWNER, then re-run harden.mjs so the new tables get row level security and grants:
--   node --env-file=.env.supabase apply-schema.mjs 002_revistas.sql && node --env-file=.env.supabase harden.mjs

CREATE TABLE public.revistas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    titulo character varying(150) NOT NULL,
    total_paginas integer NOT NULL,
    marca_id bigint NOT NULL REFERENCES public.marcas(id)
);

CREATE INDEX revistas_marca_id_idx ON public.revistas (marca_id);

-- numero 0 is the cover thumbnail, 1..total_paginas are the pages.
CREATE TABLE public.revista_paginas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagem bytea NOT NULL,
    numero integer NOT NULL,
    revista_id bigint NOT NULL REFERENCES public.revistas(id),
    CONSTRAINT revista_paginas_revista_numero_key UNIQUE (revista_id, numero)
);
