version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/backend/java'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/frontend/web'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/frontend/mobile'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
